use tauri::webview::PageLoadEvent;
use tauri_plugin_log::{Target, TargetKind};
use tauri_plugin_opener::OpenerExt;

mod badge;
mod imap;
mod mail_import;
mod oauth;
mod smtp;

// CSP note (tauri.conf.json is plain JSON, so this lives here): `script-src`
// keeps `'unsafe-inline'` because two inline scripts exist — the email
// frame's resize reporter (srcdoc, hashable) and next-themes' theme-init
// script, whose runtime-generated bytes come from minified library internals
// and cannot be pinned by a stable hash. CSP3 ignores `'unsafe-inline'`
// wherever a hash appears in the source list, so partial hashing would break
// both. Revisit if the theme provider is replaced.

fn external_navigation_plugin<R: tauri::Runtime>() -> tauri::plugin::TauriPlugin<R> {
    tauri::plugin::Builder::<R>::new("external-navigation")
        .on_navigation(|webview, url| {
            let is_internal_host = matches!(
                url.host_str(),
                Some("localhost") | Some("127.0.0.1") | Some("tauri.localhost") | Some("::1")
            );

            // App content: the tauri:// custom protocol (prod) and the dev
            // server / loopback hosts (dev).
            let is_internal = url.scheme() == "tauri" || is_internal_host;

            if is_internal {
                return true;
            }

            let is_external_link = matches!(url.scheme(), "http" | "https" | "mailto" | "tel");

            if is_external_link {
                log::info!("opening external link in system browser: {}", url);
                let _ = webview.opener().open_url(url.as_str(), None::<&str>);
                return false;
            }

            // Deny by default: anything not explicitly allowed above (odd
            // schemes, file:, javascript:, ...) must not navigate the
            // webview.
            log::warn!("blocked navigation to non-allowlisted URL: {}", url);
            false
        })
        .build()
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(
            tauri_plugin_log::Builder::new()
                .targets([
                    Target::new(TargetKind::Stdout),
                    Target::new(TargetKind::LogDir { file_name: None }),
                    Target::new(TargetKind::Webview),
                ])
                .build(),
        )
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_sql::Builder::default().build())
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(external_navigation_plugin())
        .invoke_handler(tauri::generate_handler![
            badge::set_unread_badge,
            imap::commands::imap_test_connection,
            imap::commands::imap_list_folders,
            imap::commands::imap_fetch_messages,
            imap::commands::imap_fetch_flags,
            imap::commands::imap_fetch_flags_changed,
            imap::commands::imap_store_flags,
            imap::commands::imap_move_message,
            imap::commands::imap_delete_message,
            imap::commands::imap_append,
            imap::commands::imap_fetch_attachment,
            imap::commands::imap_create_folder,
            imap::commands::imap_rename_folder,
            imap::commands::imap_delete_folder,
            smtp::commands::smtp_send_email,
            smtp::commands::smtp_send_raw_email,
            smtp::commands::smtp_test_connection,
            oauth::start_oauth_server,
            oauth::cancel_oauth_server,
            mail_import::parse_eml_file,
            mail_import::parse_mbox_file,
        ])
        .on_page_load(|webview, payload| {
            if webview.label() == "main" && matches!(payload.event(), PageLoadEvent::Finished) {
                log::info!("main webview finished loading");
                let _ = webview.window().show();
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
