import type { SqlExecutor } from "../db/executor"
import type { MessageRow } from "../db/messages"
import { getThreadWithMessages } from "../db/threads"
import { cacheKey, getAiCache, putAiCache } from "./cache"
import { AiUnavailableError, aiChat, resolveSurfaceRuntime } from "./client"
import {
  cleanUntrusted,
  fenceThread,
  UNTRUSTED_THREAD_NOTICE,
  withOutputLanguage,
} from "./prompt"
import { getOutputLanguage, isAiConfigured, isSurfaceEnabled } from "./settings"

/**
 * Thread summaries (task 4.4, ai-assistance spec "Thread summaries",
 * design D2) — the prompt/cache half of the summaries surface, consumed by
 * the reading pane (thread-view.tsx). Given an open thread, asks the
 * active provider for a concise plain-text summary and caches it under a
 * content-derived key.
 *
 * Invalidation IS the key (design D2): the cache input is the thread's
 * message-id SET — the chronological ids, order-normalized by sorting so
 * any stable re-read of the same set hashes identically. A new message
 * changes the set, which changes the key, which misses the cache — the
 * next request generates fresh (the spec's "New messages in the thread
 * SHALL invalidate the cached summary"); the old entry stays as its own
 * row (harmless, purged with the account). The active provider/model is
 * part of every key, so switching models regenerates too.
 *
 * Result shape (decided): `getThreadSummary` RESOLVES a discriminated
 * union instead of throwing — the reading pane renders every outcome
 * inline and never needs a catch path. `empty` (unknown/empty thread),
 * `unavailable` (AI not configured / summaries surface disabled — the
 * service double-checks the gate the UI hides behind), and `error`
 * (transport/provider/DB failure, `retryable` except for a
 * surface-disabled race) are all non-throwing outcomes; only truly
 * unexpected rejections propagate as `error` results too — the function
 * does not throw.
 *
 * Data boundary (spec "AI consent and data boundaries"): the prompt sends
 * only the invoked thread's own messages (sender, date, subject,
 * plain-text body — capped) and nothing else. Prompt size is bounded:
 * each body is capped at MAX_BODY_CHARS and the joined conversation at
 * MAX_TOTAL_CHARS (hard slice with a truncation marker — only reachable
 * on very long threads given the per-body cap).
 */

/** One successful summary (fresh from the provider or from the cache). */
export interface ThreadSummarySuccess {
  kind: "summary"
  /** The plain-text summary as returned by the provider (or cached). */
  summary: string
  /** True when served from ai_cache without a provider round-trip. */
  cached: boolean
  /**
   * The cache identity this summary is stored under (design D2:
   * sha256(provider|model|kind|sorted-id-set)). The reading pane keeps it
   * alongside the shown summary; a later recomputed key that differs
   * means the message set changed since.
   */
  cacheKey: string
  /** The chronological message ids the summary covers. The UI's
   * "thread changed" hint compares these with the loaded set. */
  messageIds: string[]
  /** The model that produced (or is recorded with) the summary — the
   * panel's "generated by" hint (spec: indicate AI-generated content). */
  model: string
}

/** The thread has no messages (or does not exist) — nothing to summarize. */
export interface ThreadSummaryEmpty {
  kind: "empty"
}

/** The gate is closed: hide AI affordances (spec "No provider
 * configured" / "Disable a single surface"). Defensive — the UI hides
 * first; this is the service's fail-toward-off guard. */
export interface ThreadSummaryUnavailable {
  kind: "unavailable"
  reason: "not-configured" | "surface-disabled"
}

/** A provider/transport/DB failure, reported inline with (usually) a
 * retry affordance (spec "AI caching and failure handling"). */
export interface ThreadSummaryError {
  kind: "error"
  message: string
  retryable: boolean
}

export type ThreadSummaryResult =
  | ThreadSummarySuccess
  | ThreadSummaryEmpty
  | ThreadSummaryUnavailable
  | ThreadSummaryError

export interface ThreadSummaryOptions {
  /** Skip the cache read and generate fresh (the panel's Regenerate);
   * the fresh output overwrites the entry for the same identity. */
  refresh?: boolean
}

/** The ai_cache kind for this surface (design D2). */
const CACHE_KIND = "thread-summary"

/** Per-message body cap in the prompt — bounds tokens on long mail. */
const MAX_BODY_CHARS = 3000

/**
 * Total sanity cap on the joined conversation block. With the per-body
 * cap this only engages on very long threads; the overage is hard-sliced
 * and a truncation marker appended so the model knows content is missing.
 */
const MAX_TOTAL_CHARS = 40_000

/** Marker appended when the total cap sliced the conversation. */
const TRUNCATION_MARKER = "\n\n[…conversation truncated for length]"

const SYSTEM_PROMPT = [
  "You summarize email conversations.",
  "Write a concise plain-text summary of the EMAIL CONVERSATION below:",
  "its key points, any decisions made, and anything the participants",
  "were asked or promised to do. A few sentences is enough; do not pad,",
  "do not use markdown, headers or bullet lists — plain prose only.",
  "Do not invent content that is not in the messages.",
  // The fenced thread below is attacker-controlled: state the fence
  // contract (same line every fencing surface carries).
  UNTRUSTED_THREAD_NOTICE,
].join("\n")

/** Display identity of a message's sender (never empty). */
function describeSender(message: MessageRow): string {
  const name = message.from_name?.trim()
  const address = message.from_address?.trim()
  if (name && address) return `${name} <${address}>`
  return name ?? address ?? "Unknown sender"
}

/** Format one message as a marker-indexed dated prompt block. Sender,
 * subject and body are untrusted email content: invisibles are stripped
 * before they enter the prompt. */
function formatPromptMessage(message: MessageRow, index: number): string {
  const sender = describeSender(message)
  const date = new Date(message.date * 1000).toISOString().slice(0, 10)
  const subject = cleanUntrusted(message.subject?.trim() || "(no subject)")
  const body = cleanUntrusted(
    (message.body_text ?? message.snippet ?? "").trim()
  ).slice(0, MAX_BODY_CHARS)
  return [
    `[${index}] From: ${sender}`,
    `Date: ${date}`,
    `Subject: ${subject}`,
    "",
    body,
  ].join("\n")
}

/**
 * The cache input for a thread's message-id set (design D2): the ids,
 * order-normalized by sorting (a SET, not a sequence — any deterministic
 * re-read of the same membership must hash identically), joined.
 */
function summaryInput(messageIds: string[]): string {
  return [...messageIds].sort().join(",")
}

/**
 * Summarize one thread for the reading pane (task 4.4). Loads the
 * thread's chronological messages, consults the thread-summary cache,
 * and on a miss asks the active provider (surface "summaries" — the
 * per-surface toggle and the 10/min rate-limiter bucket apply). Resolves
 * a `ThreadSummaryResult` and never throws — see the module doc for the
 * shape and the invalidation design.
 *
 * Executor-first: production callers pass getExecutor(); tests pass the
 * node:sqlite test executor.
 */
export async function getThreadSummary(
  executor: SqlExecutor,
  threadId: string,
  options?: ThreadSummaryOptions
): Promise<ThreadSummaryResult> {
  try {
    const loaded = await getThreadWithMessages(executor, threadId)
    const messages = loaded?.messages ?? []
    if (messages.length === 0) {
      // Unknown/empty thread: nothing to summarize, no round-trip, no
      // cache write.
      return { kind: "empty" }
    }

    // The gate the UI already hides behind, re-checked here (spec: AI
    // off ⇒ no requests). `isAiConfigured` is the master gate, the
    // surface toggle the per-surface one; the reason distinguishes them
    // for the (defensive) unavailable rendering.
    if (!(await isAiConfigured(executor))) {
      return { kind: "unavailable", reason: "not-configured" }
    }
    if (!(await isSurfaceEnabled(executor, "summaries"))) {
      return { kind: "unavailable", reason: "surface-disabled" }
    }
    // One resolution for the whole flow (task 2.2): `runtime.model` is
    // the tier-resolved id, used for BOTH the cache identity below and
    // the request (AiChatArgs.model) — entries are attributed to, and
    // invalidated by, the model that actually serves them.
    const runtime = await resolveSurfaceRuntime(executor, "summaries")
    if (!runtime) {
      // Same state isAiConfigured reads — unreachable in practice, kept
      // as the fail-toward-off guard (matching client.ts / 4.8).
      return { kind: "unavailable", reason: "not-configured" }
    }

    const messageIds = messages.map((message) => message.id)
    // Design D2 identity: provider/model/kind + the message-id SET. Any
    // membership change (new message, deletion) IS the invalidation —
    // and so is a tier-model switch, because the resolved model is part
    // of every key.
    const identity = {
      provider: runtime.provider,
      model: runtime.model,
      kind: CACHE_KIND,
      input: summaryInput(messageIds),
    }

    if (options?.refresh !== true) {
      const cached = await getAiCache(executor, identity)
      if (cached !== null) {
        return {
          kind: "summary",
          summary: cached,
          cached: true,
          cacheKey: await cacheKey(identity),
          messageIds,
          model: runtime.model,
        }
      }
    }

    const conversation = messages
      .map((message, index) => formatPromptMessage(message, index))
      .join("\n\n")
    const truncated =
      conversation.length > MAX_TOTAL_CHARS
        ? conversation.slice(0, MAX_TOTAL_CHARS) + TRUNCATION_MARKER
        : conversation

    const summary = await aiChat({
      // The exact model the identity above was built from — one
      // resolution for identity and request (task 2.2).
      model: runtime.model,
      // Task 2.6: the configured output language rides the system prompt;
      // unset appends nothing (the model infers from the input). Cache
      // keys do NOT fold the language in — a language switch on an
      // unchanged thread keeps serving the cached summary until
      // regeneration is asked for, the same posture as any other prompt
      // wording change.
      system: withOutputLanguage(
        SYSTEM_PROMPT,
        await getOutputLanguage(executor)
      ),
      messages: [
        {
          role: "user",
          content: [
            "Summarize this email conversation.",
            "Messages are marked [0], [1], … in chronological order.",
            "",
            // The thread is untrusted email content: fenced so the model
            // knows where the data ends (fenceThread also strips any
            // fence markers the bodies forge).
            fenceThread(truncated),
          ].join("\n"),
        },
      ],
      maxTokens: 1024,
      surface: "summaries",
    })

    // Cache the plain-text summary under the SAME identity: an unchanged
    // thread re-opens hit it instantly (spec "Cache reuse"); a Regenerate
    // overwrites this row (INSERT OR REPLACE) so the identity stays stable.
    await putAiCache(executor, {
      ...identity,
      output: summary,
      accountId: loaded?.thread.account_id ?? null,
    })

    return {
      kind: "summary",
      summary,
      cached: false,
      cacheKey: await cacheKey(identity),
      messageIds,
      model: runtime.model,
    }
  } catch (thrown) {
    // Everything below the gate maps to the inline error result — the
    // reading pane renders it with Retry (spec "Provider outage").
    // Retryable: any provider/transport/DB failure. The one
    // non-retryable case is a summaries-surface-disabled race (the toggle
    // flipped between the gate and the call — retrying cannot succeed).
    if (thrown instanceof AiUnavailableError) {
      return {
        kind: "error",
        message: thrown.message,
        retryable: thrown.reason !== "surface-disabled",
      }
    }
    return {
      kind: "error",
      message: thrown instanceof Error ? thrown.message : String(thrown),
      retryable: true,
    }
  }
}
